### ISSUE TITLE
Upgrade from Weblinks 2.0 fails

### ISSUE THREAD

**Issue by rmaiwald** [zikula-modules/Weblinks#36]
I tested Weblinks 3.0.0 (master trunk) wit Zikula 1.3.9 to upgrade from Zikula 1.2.10. Upgrading from Weblinks 2.0 fails with error message "Could not load the 'extensions' module at 'upgrade'.".

The Weblinks Installer function upgrade() correctly renames and modifies the database tables links_categories and links_links. But the following DoctrineHelper::updateSchema() fails. I am not familiar enough with the Zikula object modell to find the reasons.

Can anyone help me solve this problem?

Thanks in advance
Reiner

**Comment by rmaiwald** [comment]
I got a hint that there may be problems with tables containing blob columns (see zikula-modules/Reviews, Issue #35). Alfter deleting the table mediashare_mediadb (fortunately empty) the upgrade from Web_Links 2.0 to Weblinks 3.0.0 was fine.

Should one add this to the Zikula upgrade documentation?

**Comment by craigh** [comment]
This is not something that zikula can do anything about. The tables must be converted by the offending module - in this case, mediashare.

**Comment by craigh** [comment]
Fyi - the issue is already documented [here](https://github.com/zikula/core/blob/1.3/src/docs/en/dev/upgrading_for_developers.rst) under the LONGBLOB heading.
